### ISSUE TITLE
Textures broken in 1.12.1

### ISSUE THREAD

**Issue by davqvist** [Liahim85/MistyWorld_Open#10]
As 99% of the mods work in 1.12.1 I added your mod in my 1.12.1 world but 80% of the textures are broken. Just wanted to let you know.

Misty World alpha a 03
Forge 2456
MC 1.12.1

**Comment by Liahim85** [comment]
OptiFine?

**Comment by davqvist** [comment]
No

**Comment by Liahim85** [comment]
I do not know what's going on.
Everything is working fine for me.

**Comment by kragnoth** [comment]
Mine are broken in 1.11.2 as well.  I just updated forge to 2454, seemed to be working before that.

**Comment by davqvist** [comment]
Do you need more info or were you able to replicate?

**Comment by Liahim85** [comment]
Honestly, I do not even know what to ask.
I tested the mod on this version of forge and everything worked fine.
Soon there will be an update for 1.12.1. Perhaps the problem will disappear by itself.
Or is it a forge bug.

**Comment by davqvist** [comment]
Okay, I did a few more tests. If I load up a world with only Misty World, the textures are showing correctly. In my modpack not though. But if Optifine is added, the textures show correctly again. Now to find out what mod breaks the textures.

**Comment by davqvist** [comment]
Why haven't I thought to look through the client log earlier? Anyway here is the log: https://gist.github.com/davqvist/ca89a37f25428364a4da1b7649066652

As you can see it has tons of those errors: 
Could not load vanilla model parent 'mist:block/a_tree_planks_h' for 'net.minecraft.client.renderer.block.model.ModelBlock@6c5d8a88

**Comment by davqvist** [comment]
Something seems to break the model json, I would look into it, but your mod is not open source. I hope you can maybe figure it out.

**Comment by Liahim85** [comment]
I see the error, but I do not understand the reason.
I guess this is the influence of some other mod.
I would be grateful if you could find the culprit )
Also, I want to draw your attention to the fact that the Forge 2456 is at the beta stage.

**Comment by davqvist** [comment]
Sure Forge is beta, like 90% of the mods in 1.12, that's why I am testing them, someone has to do it :P 
Anyway, got reported from someone today that apparently knows that it is an interaction with Applied Llamagistics, not sure what exactly and I haven't tested yet, maybe you can figure out.

**Comment by davqvist** [comment]
Still happening in Forge 2484, did you investigate this issue or do you need more information? I would really include your mod in my next pack, but if the textures are broken, this obviously is problematic. Feel free to contact me if you need me to test something. Thanks for your help.

**Comment by Liahim85** [comment]
Sorry, I was carried away by the development )
Maybe it makes sense just to update the mod under the last forge. Where can I send you the file for the test?

**Comment by davqvist** [comment]
All good, all fine.
I mean I don't care, you can message on my discord https://discord.gg/QkvUrxM or my twitter https://twitter.com/davqvist if you don't want to put a link here.

**Comment by Liahim85** [comment]
Ok, ok ... I'll put the link here.
https://cloud.mail.ru/public/MPM4/vUddEeVEE

I updated it to version 2485. I fixed a couple of errors.
But hardly the reason in them ..
Did you find a mod that causes a loss of textures?

**Comment by Liahim85** [comment]
Judging by the log, which you sent earlier, the textures are not lost, but models.

"Could not load **vanilla model parent** 'mist:block/a_tree_leaves'..."

Some mod does not allow them to load or make them invisible or change them ...
I'm at a loss to say.

**Comment by davqvist** [comment]
Tested with your new version in Forge 2485 and confirm that adding Applied Energistics 2 or Applied Llamagistics breaks the textures/models. Maybe you can investigate that and/or contact one of their devs?

**Comment by Liahim85** [comment]
Did you ask the developers of these mods?

**Comment by davqvist** [comment]
Not yet, I first asking you if you had any idea. I can if you want to

**Comment by Liahim85** [comment]
I tried to run both of these mods in the eclipse and everything works as it should.
However, after the build produces the same error ...
In addition, my other mod SaltyMod also loses the texture.
I see that Applied Energistics 2 adds facades with textures of all the blocks. Could this be the reason?
Or I do something wrong.
...
Anyway, I do not know how to fix this. Perhaps the developers of Applied Energistics 2 will help.
But you better talk to them.

**Comment by Liahim85** [comment]
Wait a second.

**Comment by Liahim85** [comment]
No (

**Comment by Liahim85** [comment]
Thank you for your assistance. Fix in the process.

**Comment by Liahim85** [comment]
Update!

**Comment by davqvist** [comment]
Thanks
