### ISSUE TITLE
[INCOMPATIBILITY] Crash when mining foggy stone with a pickaxe enchanted with veining(veining enchantment mod)

### ISSUE THREAD

**Issue by Terra-B-Welch** [Liahim85/MistyWorld_Open#101]
Using version 1.2.5.3(Latest version as of this report)

Mining foggy stone with any pickaxe on the list of pickaxes that can mine it will crash the game if the pickaxe has the veining enchantment from the veining mod. Doesn't matter if it's a niobium pickaxe or another pickaxe added via the config.

The resulting error upon it breaking.
https://pastebin.com/5caSQ15r

This only occurs with foggy stone, I've not had the crash when mining pourous foggy stone or misty world ores.

Will see if the veining mod has a github to report to, and will try to report there aswell.

**Comment by Liahim85** [comment]
Ok! Thanks.
It's my fault.
Will be fixed in the next update.

**Comment by ghost** [comment]
https://github.com/arlyon/veining/issues/26

This issue was also mentioned to veining's dev.

**Comment by arlyon** [comment]
@Liahim85 thanks for sorting this out :) will close the issue on my end, but if you figure out anything else just put a comment on the linked issue above. Have a nice weekend!
