### ISSUE TITLE
[bug? complaint?] Trees cause some fps drop

### ISSUE THREAD

**Issue by DevTimur** [Liahim85/MistyWorld_Open#102]
I guess you used [Dynamic Trees](https://www.curseforge.com/minecraft/mc-mods/dynamictrees) code to generate trees?
For sure, it looks awesome, but comes with cost of fps drop.
In open field, or in mist my fps aprox. 100-120. In a middle of forest it drops to 40-60.
Sure, it's not that big of a big deal, but if I want to make big modded base in Mist, i need every frame possible.

Not sure what You or I can do to this at this point. Maybe reduce amount of trees? But that would decrease awesomeness.

So.... it's not much a report, but a general complaint about this problem. Maybe you will adress this issue in 1.16.

**Comment by Liahim85** [comment]
Not. I am not using dynamic trees...
The trees of the misty world are my personal development.
Frame drops can be due to fog rendering or chunk updates.
Anyway, I hope that both will be fixed in new versions.
