### ISSUE TITLE
Crash on Load (The mod 'Misty World' has thrown an exception.)

### ISSUE THREAD

**Issue by judicius** [Liahim85/MistyWorld_Open#103]
MistyWorld Version 1.2.5.3
Forge 14.23.5.2855
MC 1.12.2

LOG: https://mclo.gs/PHpioho#L5287
Crash: https://mclo.gs/hUP7aIc

**Comment by Liahim85** [comment]
Please read the red text in the mod description: https://www.curseforge.com/minecraft/mc-mods/misty-world
