### ISSUE TITLE
Salt & Saltpeter

### ISSUE THREAD

**Issue by InkSsskeleton** [Liahim85/MistyWorld_Open#108]
When I use both Salty Mod and MistyWorld.I could hardly find saltpeter ores in the MistyWorld,but a lot of salt ores could be found.In fact,I haven't see any saltpeter there.
So I guess saltpeter ores are replaced by the salt ones,but I'm not sure wether it is a bug.If it's not,it is important that salt can't be used to make gunpowder ,but saltpeter can.

**Comment by Liahim85** [comment]
Yes, this is done on purpose.
If a Saltymod is installed, it replaces all the saltpeter above the fog layer. However, it can be found under the fog.
