### ISSUE TITLE
Client disconnected when trying to enter portal

### ISSUE THREAD

**Issue by darkphan** [Liahim85/MistyWorld_Open#11]
Output on server: https://pastebin.com/3J7i4jLk

**Comment by Liahim85** [comment]
This is a biome conflict with "nex.world.biome.BiomeTorridWasteland"...
What does it do in a misty world?

**Comment by darkphan** [comment]
I removed the mod that added that biome, created a new world, and get the following when trying to enter the Misty World: https://pastebin.com/3SVz6g2K

**Comment by Liahim85** [comment]
Mm...
What version of mod and minecraft?
If the version is 1.11 or lower, try to delete the file mist.cfg from the configuration.

**Comment by darkphan** [comment]
MistWorld_1.12_alpha_a_03 and Minecraft 1.12
