### ISSUE TITLE
[1.11.2] Mod overrides all recipes that match crafting table. Can't make doors.

### ISSUE THREAD

**Issue by Tokeli** [Liahim85/MistyWorld_Open#12]
Forge 13.20.1.2386
Misty Worlds Alpha A03

Took me a while to pin it down, but I narrowed it down to this mod. Any recipe that uses 4 planks in a square (such as doors, or 9 planks filling the grid) instead makes a crafting table. Tested with nothing but this mod and JEI, and it still caused this. Notably, JEI still shows the correct recipe.

![image](https://user-images.githubusercontent.com/6316563/29493558-b1283062-8566-11e7-926a-2fb4929695b4.png)

**Comment by Liahim85** [comment]
Thank you for message.
Version 1.11.2 updated.
But, unfortunately, updates will not be released for this version anymore.
In version 1.12 the recipe is already fixed (nearly =)).

**Comment by 13illy** [comment]
how did you fix this issue?

**Comment by Liahim85** [comment]
I rewrote the crafting table recipe.
Version MistWorld_1.11.2_alpha_a_03+.jar

**Comment by 13illy** [comment]
Any tips on how I could bodge it for 1.10.2?

**Comment by Liahim85** [comment]
https://minecraft.curseforge.com/projects/misty-world/files/2507294
