### ISSUE TITLE
[Suggestion] Increase Sapling Drop Chance

### ISSUE THREAD

**Issue by ghost** [Liahim85/MistyWorld_Open#13]
After some experimentation, I've found that I hardly get more than 1 sapling from a tree, sometimes even none at all. If a player is to be able to farm the wood sustainably, they need to have an easier time obtaining sapling.

**Comment by Liahim85** [comment]
I'll think about it. But in the future, another mechanism will be made for the extraction of seedlings, in addition to what is already available.
Several days a year you can collect seeds and germinate them.
Thanks for the suggestion.

**Comment by ghost** [comment]
Ah, I did not know there was a time of year that was beneficial to such activities. Do you have plans to write a guide to explain all these hidden features?

**Comment by Liahim85** [comment]
No, at the moment the season does not play any role. This mechanism is still in development ...
At the expense of the guide were plans, as soon as time will appear.

**Comment by Liahim85** [comment]
Yes you are right. The chance is very small. I should increase it.
