### ISSUE TITLE
Crash starting up the game

### ISSUE THREAD

**Issue by DrDarkfire** [Liahim85/MistyWorld_Open#14]
Hey, I'm developing a pack and we were trying to use the mod but encountered a crash. One of my devs said it might have to do with Reflection and an internal field name got changed in 1.12.2
Here's the report!
[crash-2017-09-25_22.48.41-client.txt](https://github.com/Liahim85/Misty-World/files/1331688/crash-2017-09-25_22.48.41-client.txt)

**Comment by Liahim85** [comment]
No, I did not change the field in these places.
Maybe this is the influence of another mod?

**Comment by Divineaspect** [comment]
https://gist.github.com/Divineaspect/c57d1e6dd948c8832991b59d8b615978

having the same crash, nothing else is erroring.

**Comment by ghost** [comment]
I'm experiencing the same crash; https://pastebin.com/5bMva6KR

**Comment by DrDarkfire** [comment]
If I'm interpreting what my dev said to me correctly, it was the lack of change which may have been the issue.

**Comment by Liahim85** [comment]
I did not understand a bit, what should I do?
Should I just update to the latest version of forge?

This is the crash place. It's just a stairs constructor. There is nothing special.

`
public class MistBlockStairs extends BlockStairs implements IDividable {

	private final Block fullBlock;

	public MistBlockStairs(IBlockState modelState) {
		super(modelState);
		this.useNeighborBrightness = true;
		this.fullBlock = modelState.getBlock(); //line 23
	}
`

**Comment by davqvist** [comment]
field_149787_q is fullBlock if you look at the mappings.
Maybe a newer forge version made this field deprecated.

**Comment by Liahim85** [comment]
But "fullBlock" is my own field.
There should not be any crash ... It's very strange.

**Comment by davqvist** [comment]
Wait, now I am confused. I looked at the Forge Field list and the field in question in the log is named fullBlock as well. So maybe you are accidently overriding one.

**Comment by Liahim85** [comment]
Ok. I tried to rename this field.
Test it, please: https://cloud.mail.ru/public/8Jwd/BM5mJYpJ9

**Comment by davqvist** [comment]
Fixed
