### ISSUE TITLE
Crash upon attempting to sleep

### ISSUE THREAD

**Issue by ghost** [Liahim85/MistyWorld_Open#15]
Minecraft version: 1.12.1
Forge version: 14.22.1.2478
Mod version: alpha a 07
Error log: https://pastebin.com/Svgye2us

When attempting to sleep (in the overworld) to pass the night, the game crashes.

**Comment by Liahim85** [comment]
Test this version, please https://cloud.mail.ru/public/Kf5y/htpULvpg1
If everything works, I'll update the file.

**Comment by ghost** [comment]
Yes, that version fixes the bug.
