### ISSUE TITLE
Crash - Biome conflict?

### ISSUE THREAD

**Issue by ghost** [Liahim85/MistyWorld_Open#16]
Minecraft Version: 1.12.2
Forge Version:  14.23.0.2512
Mod Version: alpha_a_08
Error Log: https://pastebin.com/MQ9Npe0R

Upon entering the portal to the misty world for the first time, the game crashes. Similar crash errors occur when attempting to use the portal a second and third time (except these detail different biomes attempting to be cast to other biomes).

Removing the mod that misty world is conflicting with resolves the problem, but I'd rather have both of them together.

**Comment by Liahim85** [comment]
Try it: https://cloud.mail.ru/public/Ff6P/SVcZZfiGg
If it does not work, I have one more solution.

In addition, please check if other biomes appear in the Misty World. That would be very bad.

**Comment by ghost** [comment]
I was able to get to the dimension, but after trying to explore, the game crashed again, but with a different error this time; https://pastebin.com/Gu59K5D1

**Comment by Liahim85** [comment]
It's him, again!
This is again an old bug!
What the f**k?

Well, at least it's not biomes anymore.
Did you try to recreate the world?

**Comment by ghost** [comment]
Exact same error on a recreation of the same seed. Loading back into the world after the crash seems to not reproduce it though.

I was also unable to find any non-misty world biomes in the misty world, so it looks like that conflict is fixed.

**Comment by Liahim85** [comment]
Wait a minute!
I made a conclusion to the console from this place.
https://cloud.mail.ru/public/CjNd/pHcg1rnbK
Can you run this version, wait for the crash and send me a crashlog?

-----------
Looks like I'm late ...

**Comment by ghost** [comment]
Sadly, the log ran out of length before I could catch the crash.

"MultiMC stopped watching the game log because the log length surpassed 100000 lines.
You may have to fix your mods because the game is still logging to files and likely wasting harddrive space at an alarming rate!"

**Comment by Liahim85** [comment]
I understood...
Unfortunately, I can not write messages exactly during the bug, because I do not know the conditions under which the bug occurs.
Have to keep track of constantly.

Thanks for the help. I'll try to fix it differently, but do not know yet how )
