### ISSUE TITLE
[1.12.2] Fish issues

### ISSUE THREAD

**Issue by BuilderDan** [Liahim85/MistyWorld_Open#18]
Hello,

Love your mod and everything about it, super creative and look forward to the future, but I ran into a slight bug with the JustAFewFish mod, they appear to spawn in the toxic pools at the bottom of the canyon, I'd love to see compatibility with this mod, so that they don't spawn in there and instantly die. (Remove spawns possibility).

**Comment by Liahim85** [comment]
Yes, I know about this problem and will try to correct it.
However, this mod does not have open source code. I'll try to contact the author.

**Comment by BuilderDan** [comment]
Thanks for putting in the effort! Look forward to the future of your mod.

**Comment by Liahim85** [comment]
Tried to fixed it. Update. Let me know if it's not fixed.
