### ISSUE TITLE
1.10.2 Crafting table recipe (Survival breaking bug!)

### ISSUE THREAD

**Issue by 13illy** [Liahim85/MistyWorld_Open#19]
So you can craft a crafting table with 4  or even more default Minecraft wood planks adding more wood doesn't change the recipe this stops the ability to make doors. 
![2017-11-04_21 41 08](https://user-images.githubusercontent.com/32988918/32409787-82571020-c1aa-11e7-90fa-717b73b1eb02.png)
![2017-11-04_21 41 13](https://user-images.githubusercontent.com/32988918/32409788-85a7756c-c1aa-11e7-887b-6abe8d07fa97.png)
no other mods instaled other than NEI 1.10.2
Any idea why this might be?

**Comment by Liahim85** [comment]
This bug has long been fixed in versions 1.11 and 1.12.
But, unfortunately, the development of the mod for version 1.10 is discontinued.

**Comment by 13illy** [comment]
So I guess there is no reason to add the mod to a modpack or just your game in general?
