### ISSUE TITLE
Cross-mod CTD with ProjectE

### ISSUE THREAD

**Issue by trevorjd** [Liahim85/MistyWorld_Open#21]
Greetings,

We've discovered a tooltip render related CTD bug when mousing over a particular bucket in the ProjectE transmutation table. The ProjectE author says it's related to the way misty is handling tooltips. Would you have a look, please?

https://github.com/sinkillerj/ProjectE/issues/1624

Cheers!

**Comment by Liahim85** [comment]
Hi! It's already fixed in MistWorld_1.12.1_alpha_b_02.jar
