### ISSUE TITLE
Systematic errors in interdimensional teleportation induced by this mod

### ISSUE THREAD

**Issue by soulhakr** [Liahim85/MistyWorld_Open#23]
When anyone enters or leaves dimensions created by other mods, such as using the _Spectre Key_ from _Random Things 4_, or the _Compact Machines 3_ dimension, the location where the player entity spawns in is not where it's supposed to be. So going into the created dimensions, you don't show up in the center of the structure (this is more evident when you're in creative mode because you may not get immediately shunted out of the dimension.) And when leaving the dimension, you may not return to the location in the overworld from whence you came.

**Comment by Liahim85** [comment]
Tried to fixed it. Update. Let me know if it's not fixed.
