### ISSUE TITLE
tessellating block in misty world.

### ISSUE THREAD

**Issue by 13illy** [Liahim85/MistyWorld_Open#24]
1.10.2_alpha_a_04 
after 10 seconds of being in the misty world chrashes with a tessellating block error. very likely that this is a issue with a difrent mod has i have it running in a modpack but would be a exsplanation to the cause would be very helpful.
[crash-2017-12-22_15.01.20-client.txt](https://github.com/Liahim85/MistyWorld/files/1582824/crash-2017-12-22_15.01.20-client.txt)

**Comment by Liahim85** [comment]
Update
