### ISSUE TITLE
Crash when loading mod

### ISSUE THREAD

**Issue by avescarelo** [Liahim85/MistyWorld_Open#25]
Hello, I tried installing your mod on my server but I couldn't do it :( please Help, here is crashlog
[crash-2017-12-30_01.54.49-server.txt](https://github.com/Liahim85/MistyWorld/files/1594096/crash-2017-12-30_01.54.49-server.txt)

**Comment by Liahim85** [comment]
Привет! Что-то я не увидел в крашлоге упоминания о моём моде )
Ты уверен, что краш вызывает именно он?

**Comment by avescarelo** [comment]
Привет, данный краш возникает лишь при добавлении мода.

**Comment by Liahim85** [comment]
Хз... Что-то связанное с биомами... Но не из-за меня. Возможно конфликт с другим модом...
В краше я нашёл только упоминание о spongepowered...
