### ISSUE TITLE
Portal working from any dimension?

### ISSUE THREAD

**Issue by davqvist** [Liahim85/MistyWorld_Open#27]
Not sure if a bug or intended, but I planned to use Misty World for my modpack with custom progression and noticed that the portal doesn't form in my custom dimension. Can you add a config for whitelisted dimensions where you can teleport from to the Misty World?

**Comment by Liahim85** [comment]
A good idea )
But the timing of the implementation can not exactly say.
This will require a more profound alteration of the portal than it may seem.

**Comment by davqvist** [comment]
I would love you forever if you could add that. Would hate to remove your mod just because of that hindrance.

**Comment by Liahim85** [comment]
Update.
