### ISSUE TITLE
[Bug] Structures Generation & Trees

### ISSUE THREAD

**Issue by ghost** [Liahim85/MistyWorld_Open#29]
As of mod version 1.12.2 alpha b 04 (I'm not sure if this affects other versions of the mod), structures added by any structure generation mod withthe SURFACE type generator will generate on top of tree blocks, rather than removing the tree like they do for vanilla trees. I've found adding the living trunk version of the trees to the oredict entry woodLog (or whatever it was for logs) fixes this, but has the unintended side effect of making these blocks appear in recipes that use woodLog as an ingredient.

**Comment by Liahim85** [comment]
Perhaps this is due to the fact that the foliage is still a full block, and the structures think that it can appear on it. Or I misunderstand the problem.
