### ISSUE TITLE
Respirator when Left-handed.

### ISSUE THREAD

**Issue by Kisutora** [Liahim85/MistyWorld_Open#3]
If you have set your player to be left-handed from the skin customization options the respirator overlaps with the dual wielding slot as it switches sides.
![left-handed](https://user-images.githubusercontent.com/22685232/28433910-12f80a12-6d96-11e7-99c3-0e6fbb1a006b.png)
Would really appreciate it if it would check whether you are right- or left-handed and switch sides accordingly. Thanks!

**Comment by Liahim85** [comment]
Yes! Thank you for your comment.
I will do this as soon as I return to the development of the mod.
In plans to make the setting for the customization slot position.

**Comment by Kisutora** [comment]
Great! Thank you. :)
