### ISSUE TITLE
[Request] Crafting Recipe for mist:stone

### ISSUE THREAD

**Issue by ghost** [Liahim85/MistyWorld_Open#31]
It would be nice if there were natively a recipe to craft the smooth mist stone from porous stone or cobblestone. While this is easy enough to add as a pack dev, it would be nice if it were native.

**Comment by Liahim85** [comment]
I'm thinking about how it's best to implement. An ordinary recipe is too simple and not interesting. In the future there will be something else, perhaps.
But so far, the upper stone can be obtained with the charm "Silk Touch".
