### ISSUE TITLE
[Question] Future Dungeon Plans

### ISSUE THREAD

**Issue by ghost** [Liahim85/MistyWorld_Open#32]
For the future planned dungeons; are you going to make them generate below or above the fog layer, and are you planning on having them generate on the surface of the landscape or underground?

I ask because I'm considering building some dungeon structures to spawn in the Misty World for my modpack and want to know in advance so I can spawn them where the default dungeons (when they exist) aren't.

**Comment by Liahim85** [comment]
Dungeons are a distant future )
However, they plan to be very diverse. And above the layer of fog, and under it. Both on the surface and under the ground. However, I can say that only small structures will appear above the ground.

**Comment by ghost** [comment]
When you do eventually get there, could you please include a config option to disable their generation?

**Comment by Liahim85** [comment]
I will take note of your request. But only if it does not contradict the main idea.
