### ISSUE TITLE
Many Mitsty World recipes conflict with many mods by default

### ISSUE THREAD

**Issue by NotAVerb** [Liahim85/MistyWorld_Open#34]
According to JEI Misty World adds recipes to create a wooden door, another for a trapdoor, and one for a crafting table.
These recipes break lots of mod recipes that use their own wood by default.
Could these recipes be reimplemented specifying the use of Misty World materials (tree timber) only?

The recipes for wooden tools also cause issues with mods. I don't know why, seeing as the recipe doesn't call for "any plankWood". I don't know what Misty World is doing exactly, but it is still generating a large list of recipes that cycle in JEI, and by monitoring it for long enough I've spotted Betweenlands and Natura woods in the recipes.

**Comment by Liahim85** [comment]
You can fix it yourself by opening file: `assets\mist\recipes\_constants.json` and deleting the lines:
`,
            {
                "type": "forge:ore_dict",
                "ore": "plankWood"
            }
`

**Comment by NotAVerb** [comment]
I don't have `assets\mist\recipes\_constants.json` in my minecraft instance folder. This might be because I'm using MultiMC. There's an assets folder in the MultiMC folder but it has no \mist subfolder. There's only \indexes, \objects, and \skins.

**Comment by Liahim85** [comment]
Open MistyWorld.jar with any archiver and there you will find a folder )

**Comment by An-Sar** [comment]
This is a problematic solution for mod packs that get pushed through twitch.
Sorry to comment on a closed issue.
