### ISSUE TITLE
[Crash] JustAFewFishAPI when Biomes O Plenty is present

### ISSUE THREAD

**Issue by An-Sar** [Liahim85/MistyWorld_Open#35]
the crash indicates JustAFewFishAPI, however this is triggered only when Biomes O Plenty is installed.

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Misty World (mist)
Caused by: java.lang.NoClassDefFoundError: com/tmtravlr/jaff/api/JustAFewFishAPI
    at ru.liahim.mist.common.Mist.initCompatibilityMod(Mist.java:80)
    at ru.liahim.mist.common.Mist.init(Mist.java:68)
```
forge-1.12.2-14.23.2.2623-universal.jar
MistWorld_1.12.1_alpha_c_01.jar

occurs with both of these versions, does Not occur with the previous MistWorld release
BiomesOPlenty-1.12.2-7.0.1.2315-universal.jar
BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar

full crash:
https://pastebin.com/fEQKa2L3

**Comment by Liahim85** [comment]
Oops! I wonder how it could happen?
Fixed & update!
