### ISSUE TITLE
Niobium Tools don't have proper toolclasses and don't extend the respective tool subclasses

### ISSUE THREAD

**Issue by DaedalusGame** [Liahim85/MistyWorld_Open#37]
All of the Niobium Tools appear to not have toolclasses set and they don't extend from the respective tool subclasses (like ItemAxe, ItemPickaxe, ...) which makes them unrecognized by most mods detecting specific tools, in this case I found this because HCLumber from Better With Mods doesn't properly detect niobium axes.

**Comment by Liahim85** [comment]
Changed it, thanks )
