### ISSUE TITLE
Worldgen doesn't fire relevant forge events

### ISSUE THREAD

**Issue by DaedalusGame** [Liahim85/MistyWorld_Open#38]
Hey, sorry to bother you again, but it looks like Misty World generation does not fire events like DecorateBiomeEvent and other such things. I think I've identified one cause, and it's because while your BiomeDecorator extends the vanilla class, it does not call super.genDecorations. If you're worried about the vanilla BiomeDecorator generating vanilla features in your world, you can disable these by setting the relevant fields to 0 or negative numbers (ex. bigMushroomsPerChunk = 0).
Thanks in advance if you're going to look into this.

**Comment by Liahim85** [comment]
Yes thank you.
I was going to do it in the future. Just have a lot of other things.
I think it will be easier to manually fire the event.
