### ISSUE TITLE
[Dupe bug]Infinite MW planks and timber by crafting to/from timber

### ISSUE THREAD

**Issue by thephoenixlodge** [Liahim85/MistyWorld_Open#39]
Currently the mod includes recipes to convert between the planks and timbers for the various woods. The problem is that it currently is set up as 4 timber -> 1 plank and 1 plank -> 8 timber, so crafting timber from a plank gives enough to recraft 2 planks.

**Comment by Liahim85** [comment]
But this is not the case. At me all works as it is necessary.
Are you sure that another mod does not affect this?

**Comment by thephoenixlodge** [comment]
Blegh I have no idea, a fresh instance with just MW and JEI indeed doesn't have the problem, but I have not the slightest idea what mod could be affecting it. I'm tweaking the recipes myself anyway, so whatever.
