### ISSUE TITLE
Game crashed while exploring the Misty World.

### ISSUE THREAD

**Issue by Kisutora** [Liahim85/MistyWorld_Open#4]
Just like that when loading the world somewhere deep in the world, the game suddenly crashed and will just crash again when trying to enter the save file again.
[crash-2017-07-20_23.00.33-client.txt](https://github.com/Liahim85/Misty-World/files/1163570/crash-2017-07-20_23.00.33-client.txt)
[crash-2017-07-20_23.01.47-client.txt](https://github.com/Liahim85/Misty-World/files/1163557/crash-2017-07-20_23.01.47-client.txt)

**Comment by Liahim85** [comment]
Unfortunately, I can not pinpoint the cause of the crash without saving. I suppose that one of the trees was generated incorrectly and an infinite loop was formed. I'm not even surprised that it was just a tropical tree ))) It is one of the most difficult in generation.
...
You can try to delete the folder with a misty world (DIM69), change the seed in the config file and go into the world again.

**Comment by Kisutora** [comment]
Alright, I'll try that if I ever encounter a crash again since I already deleted the world since it was just a test world. Thank you!
