### ISSUE TITLE
Portal Middle block breaks in one hit

### ISSUE THREAD

**Issue by DaedalusGame** [Liahim85/MistyWorld_Open#40]
I'm not sure about this, the way nether portals work the portal block is unbreakable, not sure if this warrants fixing though. You do lose a whole block of gold in one click though, so I feel like I should bring this up in case it's not intended that way

**Comment by Liahim85** [comment]
You need to be careful )))
But I'll think about it. Perhaps it is worth making the portal unbreakable.
