### ISSUE TITLE
Crash with Chisel & Bits and JEI

### ISSUE THREAD

**Issue by davqvist** [Liahim85/MistyWorld_Open#41]
Misty World alpha c 04 (I know not current version but I didn't see anything in the changelog of the new version yet)
Forge 2688

I link you this issue: https://github.com/davqvist/Exoria/issues/173
People crash because of a certain item appearing in JEI, it seems that it must be a Misty World item and Chisel & Bits will let it crash. Can you figure out from this information what it might be?

**Comment by davqvist** [comment]
Chisel & Bits dev said following:

> Looking it it looks like ru.liahim.mist.init.BlockColoring is being called for "Air" I imagine that the mod is miss-registering its color handler for air, since that makes little sense, probably an order of operations issue where it gets registered before the item they intended to register or something else.

**Comment by TeamDman** [comment]
Had a peek at the jar, looks like the BLOCK_ITEM_COLORING assignment where it overrides some method in a new IItemColor isn't checking whether a stack is empty, or whether it is an instanceof ItemBlock, before casting it to one. Either adding the checks, or fixing the order of operations issue should resolve it.

Modpack where I'm having the same issue:
https://minecraft.curseforge.com/projects/exoria
Crash report:
[crash-2018-05-16_17.46.48-client.txt](https://github.com/Liahim85/MistyWorld/files/2010968/crash-2018-05-16_17.46.48-client.txt)

**Comment by PaulMurrayCbr** [comment]
Me too: https://pastebin.com/PGk5Z6MF

**Comment by Liahim85** [comment]
Try to fix...
