### ISSUE TITLE
Duplicate Language key with some mods

### ISSUE THREAD

**Issue by TartaricAcid** [Liahim85/MistyWorld_Open#46]
There are some dupliacte language key with other mods.
`item.ash.name`
- biomesoplenty: `Pile of Ashes`
- mist: `Ash`  
- primal: `Ash`  

`tile.pine_stairs.name`
- biomesoplenty: `Pine Wood Stairs`  
- mist: `Foggy Pine Stairs`  

`tile.willow_stairs.name`
- biomesoplenty: `Willow Wood Stairs`  
- mist: `Weeping Tree Stairs` 

`tile.acacia_log.name`
- missing_pieces: `Acacia Log`  
- mist: `Umbrella Tree Wood`  

`tile.birch_log.name`
- missing_pieces: `Birch Log`  
- mist: `Forest Deceiver Wood`  

`tile.oak_log.name`
- missing_pieces: `Oak Log`  
- mist: `Foggy Oak Wood`  

`tile.spruce_log.name`
- missing_pieces: `Spruce Log`  
- mist: `Prickly Tree Wood`  

`tile.willow_log.name`
- missing_pieces: `Willow Log`  
- mist: `Weeping Tree Wood`  

`tile.stone_porous.name`
- mist: `Porous Foggy Stone` 
- thaumcraft: `Porous Stone`

**Comment by Liahim85** [comment]
Thank you! Does this prevent proper translation?
It seemed to me that minecraft separated the language files into separate mods.
Perhaps I should add a "mist" prefix to them.

**Comment by TartaricAcid** [comment]
In fact, language files are handled in a hashmap, so each language key should be unique.

**Comment by Liahim85** [comment]
Thank you, I'll take this into account in the next updates.
