### ISSUE TITLE
Issue with Astral Sorcery and Erebus

### ISSUE THREAD

**Issue by zEpiixz** [Liahim85/MistyWorld_Open#48]
https://paste.dimdev.org/afasujaqiz.mccrash

Crash when joining a world

**Comment by Rikshy** [comment]
This was a bug in Erebus, and was fixed in december.

Edit: nevermind it's still there ._.

Edit2: It got fixed in december, but it's not released yet
https://github.com/vadis365/TheErebus/commit/7be4cbe16075ad3e7c00c1e317bb632a782086b1#diff-b22c311cf5d61c8f1cb8eeea21346d38L118

**Comment by Liahim85** [comment]
Thanks for the information )
