### ISSUE TITLE
[Request] Config to disable Endermen dropping portal stones

### ISSUE THREAD

**Issue by thephoenixlodge** [Liahim85/MistyWorld_Open#49]
I'm working on a skyblock pack, and would like to make Enderman available much earlier than I want players to be able to go into the Misty World, but as far as I can find, it's not possible to disable it currently due to the special handling of giving it only once. If it was in the enderman loottable I could disable it with LootTweaker, but it isn't, and there's no config for it currently either. As such, could this please be added as a config option, so that us pack devs can control access to the dimension a bit more.

**Comment by Liahim85** [comment]
Of course it can be done ...
Can it wait until the next update or need it in the near future?

**Comment by thephoenixlodge** [comment]
It's not hugely urgent, so can wait until the next update fine

**Comment by Liahim85** [comment]
Added config parameter )
