### ISSUE TITLE
Crash When Looking At Portal

### ISSUE THREAD

**Issue by ChloeDawn** [Liahim85/MistyWorld_Open#5]
Crash to desktop when looking at portal with HWYLA installed.

**Mod version:** [alpha_a_02](https://minecraft.curseforge.com/projects/misty-world/files/2459343)
**Forge version:** [1.12-14.21.1.2443](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2443/forge-1.12-14.21.1.2443-changelog.txt)

**Crash report:** [pastebin/aDRLe9qS](https://pastebin.com/aDRLe9qS)

**Comment by Fundryi** [comment]
Was going to report the same :) Hope this can be fixed quick :P

**Comment by Liahim85** [comment]
Updated, but not tested.
Please, write if the error is not fixed.

**Comment by Fundryi** [comment]
Yea sorry forgot to write its fixed.
