### ISSUE TITLE
Possible Incompatibility with Aqua Munda

### ISSUE THREAD

**Issue by mr-poyo** [Liahim85/MistyWorld_Open#52]
Hello,

Received this crash on world-gen:

Removing Aqua Munda fixes the issue, or removing Misty World fixes the issue.

https://pastebin.com/0Mj2BdFk

Thank you for the mod!

**Comment by Liahim85** [comment]
Thank you for message.
This is really a very vulnerable part of the code. It will be necessary to add there some additional checks.
