### ISSUE TITLE
Worldgen not Firing Forge Decoration events, limits compat with tweaker mods in packs

### ISSUE THREAD

**Issue by thephoenixlodge** [Liahim85/MistyWorld_Open#53]
I've been trying to have Botania's mushrooms generate in the Misty World using tweaker mods that can do decoration functions, but it currently cannot work, seemingly due to a lack of Forge events being fired upon doing your worldgen. Specifically I've tried using both BiomeTweaker and CoFHWorld to accomplish this.
This is similar to https://github.com/Liahim85/MistyWorld/issues/38 but as yet it still seems to not be implemented which limits a bit what pack devs can do with the mod to integrate others with it.

**Comment by Liahim85** [comment]
Thank you for message.
It seemed to me that I added events. Perhaps not everywhere. Or something went wrong.
I will try to fix it in the following updates.

**Comment by Liahim85** [comment]
Added Pre & Post Event to BiomeDecorator.
Will this solve the problem?
https://cloud.mail.ru/public/Jma9/2VUSxZ318

**Comment by Liahim85** [comment]
Update & Close

**Comment by thephoenixlodge** [comment]
Just tested and that does seem to be working
