### ISSUE TITLE
[Bug]  Crash during world creation

### ISSUE THREAD

**Issue by mr-poyo** [Liahim85/MistyWorld_Open#54]
Edit: Crash report looks similar to #52, although aqua munda is not in this particular pack. 

I am not sure where the conflict is but I started working on a large modpack and am getting this crash during world-creation:

https://pastebin.com/Sm6vEfmc

Disabling MistyWorld fixes the issue. 
Will update if I can identify which mods are conflicting as I love this concept and would love to have it as an exploration point of interest.

**Comment by Liahim85** [comment]
Yes, I understand you!
This is a weak spot associated with the campfire.
I will try to solve this problem. Not sure very soon.

**Comment by Liahim85** [comment]
Check this version, please.
If everything works, I'll post it in public.
https://cloud.mail.ru/public/Jma9/2VUSxZ318

**Comment by mr-poyo** [comment]
Thank you for your support, I am still receiving this crash: https://pastebin.com/RqeVbJzu

I unfortunately dropped a handful of mods from my previous build due to tps lag (still troubleshooting by the way) so I am unable to replicate an exact duplicate test. However, in #52 I was able to find the same crash with Aqua Munda so I tested Aqua Munda with the new MistWorld_1.12.2_alpha_c_09.jar.

**Comment by Liahim85** [comment]
Thanks for the test!
Regarding the current crash and crash #52, it seems to me that this is an Aqua Munda problem, since the error itself occurs in its classes.
