### ISSUE TITLE
[1.12.2] Crash when killing an Enderman

### ISSUE THREAD

**Issue by PrettyMuchTara** [Liahim85/MistyWorld_Open#57]
I got a crash while I killed an Enderman. Before any loot generated, the game froze and ultimately turned into the crash. Happened twice in a row. 

Used versions:
Forge: 14.23.5.2838
Misty World: alpha_c_09

Crash Report: https://pastebin.com/Xabkyb0c
Config file for Misty World: https://pastebin.com/3hvxiRhZ

[My instance has many mods, and also Triumph which changes the advancement system. Maybe the source is the compat]

**Comment by Liahim85** [comment]
It seems to me that the problem is precisely compatibility, since crash occurs when trying to find an advancement.
