### ISSUE TITLE
World loading takes forever on both new and pre-existing worlds

### ISSUE THREAD

**Issue by katubug** [Liahim85/MistyWorld_Open#58]
I am heartbroken to report that there's some issue with your mod and my modlist, that causes every world load (of the overworld, haven't tested other dimensions) to hang for close to a minute before the terrain actually appears.

After two days of testing, I've finally nailed it down to being this mod, but I can't figure out what the conflict is. Misty World by itself does not have the issue. I made a new instance with just MW and tested my whole modlist as such: put in 5 mods at a time, then loaded a world to see if the issue occurred. If the issue did not occur, I'd remove those 5 mods and replace them with the next 5.

Doing this, I went through the whole modlist without being able to replicate the bug. But putting everything back together does cause the issue. So I'm genuinely baffled. I made [this reddit post](https://www.reddit.com/r/FeedTheBeastCrashes/comments/dxwgql/terrain_takes_close_to_1min_to_load_in_new_and/) about it to see if anyone else could help, but no dice.

For sake of ease, I'll copy some of the information here:

> My other pack, which is big (200+ mods), does not have this issue, so I do not think it's related to my computer.
> 
> It happens regardless of launcher used, and regardless of whether the world is newly created or pre-existing. Using both default world generator preset and the one custom to one of my biome mods are the same in terms of loading time.
> 
> I tried to isolate the issue by adding only a few mods at a time until the hangup began to occur, and then testing only those most recently added in. However, removing the mods that this method seemed to implicate did not fix the issue either. I also tried downgrading forge from 2847 to 2838 in case that made a difference - it did not.
> 
> The issue occurs regardless of whether or not the configs are edited or default. I do not currently have any script files or resource packs. I haven't done any tests involving my video settings or other options.
> 
> - Here's everything in my mods folder, with versions (you'll note that some of them have been disabled during my testing): https://pastebin.com/tAih4kew
> - Here's a gif of what's happening: https://gfycat.com/prestigiousbasicbats
> - Here's my latest.log: https://paste.ee/p/6Awqh
> - My debug.log: https://paste.ee/p/dHqd6
> - My loading-log.log (from Loading Profiler): https://pastebin.com/eAKgGrKa
> 
> Edit: Lowering my draw distance has no effect.

So, I'm out of ideas. I'm incredibly bummed, because this mod fits my needs absolutely perfectly aside from this issue. If there's any way you have of figuring out what could be causing the problem, it would make me very happy.

Please let me know if there's any other information I can provide.

**Comment by Liahim85** [comment]
I'm sorry. I have no idea why this is happening.
I suggest gradually adding mods from the list until the error starts to appear.
Perhaps not two, but three modes are in conflict О_о

**Comment by hohserg1** [comment]
@katubug try to put in 10 mods at a time, iterate all modlist, if it does not reveal the problem, try to group mods by 20...
When you find problematic group of mods try to remove mods by one. If problem wanished after next removing, return this mod and try to continue with other mods.
As result you obtain minimal group of mods which cause a problem

**Comment by katubug** [comment]
Okay, so I did some more testing today, and the findings are... weird. Here's a pastebin of each step: https://pastebin.com/Fd89C9Qz

To sum up - the amount of time it takes to load the terrain is based on how many of the following problematic mods are in the pack: Quark/AutoRegLib, Better With Mods, Better With Addons, Fish's Undead Rising (questionable, very minor difference), FoodFunk/WumpleUtil, Vanilla Food Pantry.

As far as I can tell, those mods don't have anything particular in common, at least not that I can think of.

Again, I'm stumped. I've never seen an issue like this before. The only insight that I have to add is that it almost seems like Misty World might be ending the loading screen before the world is ready? Because without MW, the game takes a while to load, but it stays on the loading screen for most of the time. That still doesn't explain why it would take almost a minute to load, though. For comparison, my 228-mod kitchen sink pack with significantly more worldgen, entities, and large content mods, takes 45 seconds from "Create World" to terrain appearing, but the loading screen covers all but a few seconds of that.

Additionally, something I noticed during these tests was that during the long load, the sun would progress through the sky, but when the terrain loaded, it would snap back down to its original position. I have no idea if that's at all relevant, I'm just throwing things at the wall to see if they stick.

So, hopefully some of this helps somehow. Thank you for your time!

**Comment by Liahim85** [comment]
The movement of the sun only says that the client continues to work while the server is going on for some long process. It may be generation, or it may not.
And the Misty World does not affect the loading screen. At least I didn’t do it intentionally.

**Comment by hohserg1** [comment]
> the amount of time it takes to load the terrain is based on how many of the following problematic mods are in the pack:

It's like a cascade chunk loading

**Comment by Liahim85** [comment]
For the Misty World, cascading lag is completely normal, and I specifically turned off this log, but it can be turned on in configs.
However, the lag also occurs in the Overworld.

**Comment by katubug** [comment]
Yeah, I don't think this is cascading worldgen lag. I've used a lot of mods with similar issues in the past (cough Recurrent Complex cough) and this issue is totally new to me. I genuinely don't know what it could be, but I can't afford to cut all the conflicting mods from the list. I'm going to keep following Misty World and I'll try it again when there's an update and see if the issue still occurs.

**Comment by Liahim85** [comment]
Hello! I want to check one guess.
Can you test this file?
https://cloud.mail.ru/public/TU9H/5HBsn8CwR
There may be errors, but do not pay attention to it.

**Comment by katubug** [comment]
Yes! That works perfectly! :D

**Comment by Liahim85** [comment]
Good! But don't use this file. It's buggy.
I will fix it differently and send the working file...

**Comment by katubug** [comment]
No problem, understood. I'm still in early development anyway, so I won't need to work on it for a while.

Thank you so much for looking into this! I'd been trying to find a suitable replacement for a dimensional mod for this pack, and honestly nothing fit like your mod does. I guess I had my heart set on it. Looking forward to the update, thank you again! :)

**Comment by Liahim85** [comment]
Test this file, please: https://cloud.mail.ru/public/5E8j/4f98ZwaHV
If everything is fine, then you can use it.
These changes will be reflected in the next update.

**Comment by katubug** [comment]
Seems to work fine! Thank you very much, looking forward to the full update :D

**Comment by katubug** [comment]
Hey, I just wanted to follow up with you about when this patch might release? I'm not technically in any hurry because I'm not releasing the modpack for at least another month, but in order to include this with the modpack, I'm fairly certain that the update needs to be on CurseForge.

I definitely don't want to seem like I'm rushing you, though, just curious if you had an ETA at all. :) I know this is a busy time of year what with finals and holidays and everything else. I hope you're having a good December so far!

**Comment by Liahim85** [comment]
I do not have an exact deadline, however, I also would not want to update the mod just once again. Perhaps I will have time to finish the update by the time you finish the modpack. If not, write to me and I will post the patch to the public.

**Comment by katubug** [comment]
I understand! Thank you very much, that seems completely reasonable. I really appreciate your hard work! Have a lovely holiday season :D
