### ISSUE TITLE
Misty World Spamming console. [1.12]

### ISSUE THREAD

**Issue by Fundryi** [Liahim85/MistyWorld_Open#6]
Log: [Link](https://gist.githubusercontent.com/Fundryi/9400a1a8b2c569981237b8e2bf8f7eb0/raw/a97282e79f0d74eba6652ef9484704a66e81c596/Spammmm)

**Comment by Liahim85** [comment]
Wow!
The probability of this error is described in the warnings, paragraph 2:
"There may be conflicts with other mods that add biomes or **change the time**."
Someday I will remake this mechanism.

**Comment by Liahim85** [comment]
Will be fixed in the version alpha_b_01
