### ISSUE TITLE
ClassNotFound exception during loading, game hangs on initialization

### ISSUE THREAD

**Issue by katubug** [Liahim85/MistyWorld_Open#60]
Hi! I'm testing out the major suite of mods for my modpack, and the game seems to be failing to initialize when it attempts to process Misty World. The only unusual thing I see in the log is a stacktrace (line 14):
```
[12:21:09] [main/ERROR]: Coremod MistHookLoader: Unable to class load the plugin ru.liahim.mist.hooklib.hooks.MistHookLoader
java.lang.ClassNotFoundException: ru.liahim.mist.hooklib.hooks.MistHookLoader
```

Here is my full latest.log: https://hastebin.com/nuqunebeta.md

The game loads fine when Misty World is not included.

The issue does not occur with just Misty World, but as of this moment I don't have the time to test mods and find which is the conflict. I will do so later, but in the meantime I am hoping you may be able to give me some guidance.

The version of Misty World I am using is the test file you gave me in the other thread, forge version 2847. I can't get a full modlist at the moment, but please let me know if it's needed.

**Comment by Liahim85** [comment]
Try this https://cloud.mail.ru/public/2sSg/2WMcVwpsU

**Comment by Liahim85** [comment]
Try this https://cloud.mail.ru/public/4UYD/3h5XD3DKd

**Comment by katubug** [comment]
Yep, that works! Thank you very much!
