### ISSUE TITLE
[Suggestion] Boss and dungeons

### ISSUE THREAD

**Issue by Zack7292** [Liahim85/MistyWorld_Open#62]
Now that your fantastic mod have finally gotten mobs, i think you should add bosses and dungeons, so the ppl have a goal when they explore you dimension, nests poisonous labyrinth, i think your mod could contains lot of fantastic dungeon like never seen!

(Btw really like the mobs u did a fantastic job on them)

**Comment by Liahim85** [comment]
There are already small dungeons there.
