### ISSUE TITLE
Crash with Tinker's Construct

### ISSUE THREAD

**Issue by LemonJamTart** [Liahim85/MistyWorld_Open#63]
I am experiencing a progression-halting crash when using this mod with Tinker's Construct. The crash occurs when doing anything with any of the Tinker's blocks- anything from trying to put stencils into a pattern chest to trying to build tools will cause this crash, and I say "trying" because the crash occurs when any item is inserted into any of the blocks whatsoever. Crashlogs at the following links.
[Tool Forge Crash](https://pastebin.com/Sb2W7QPQ)
[Part Builder Crash](https://pastebin.com/6R8P40ez)
[Pattern Chest Crash](https://pastebin.com/aT8qH8Y4)
[Crafting Station Crash](https://pastebin.com/yubyhhQX)

Any help at all is appreciated. Thank you in advance for your time.

**Comment by Liahim85** [comment]
Yep! It's my fault!
I'll try to do something.
And you can try to disable advanced fog renderer.

**Comment by LemonJamTart** [comment]
Wonderful, thank you so much for the quick response. Turning off advanced fog rendering fixed the crashing. Excellent work on this mod, by the way- simply a delight to play with.

**Comment by Liahim85** [comment]
Fixed!
But I will post the update as soon as I deal with another bug.

**Comment by Liahim85** [comment]
Update!

**Comment by Liahim85** [comment]
Update!
