### ISSUE TITLE
Flowerpots duplicate items

### ISSUE THREAD

**Issue by SunnyOpossum** [Liahim85/MistyWorld_Open#66]
Planting tree seeds, saplings, or mushrooms from Misty World in a flowerpot does not take the item from your inventory in survival mode.
![2020-04-18_23 46 47](https://user-images.githubusercontent.com/60582335/79678964-1e9c6200-81cf-11ea-8143-5245bce17ff6.png)
![2020-04-18_23 47 22](https://user-images.githubusercontent.com/60582335/79678966-29ef8d80-81cf-11ea-893c-a1112a9572bc.png)

![2020-04-18_23 47 33](https://user-images.githubusercontent.com/60582335/79678969-2f4cd800-81cf-11ea-97aa-b21217858117.png)

**Comment by Liahim85** [comment]
This is definitely a bug!  Thanks :)

**Comment by SunnyOpossum** [comment]
No problem, love the mod! : )

**Comment by Liahim85** [comment]
Fixed
