### ISSUE TITLE
Ctrl-Placing Cobblestone Places a Different Block...

### ISSUE THREAD

**Issue by TheVisionaryOne** [Liahim85/MistyWorld_Open#67]
Hey, I'm not entirely sure that this problem is added by Misty World (since it doesn't have any visible block ID or presence in the creative menu), but by process of elimination, I think it's from Misty World.

Whenever I ctrl-place a cobblestone block, this block places instead:
![2020-04-21_15 15 12](https://user-images.githubusercontent.com/56095032/79919633-9f33ac00-83e3-11ea-8211-b64d13344682.png)

It's pretty annoying, since it changes the way you interact with such a common vanilla item. It would be fantastic if this only happened in the Misty World dimension, or if there was a way to turn this feature off in the config.

**Comment by Liahim85** [comment]
It is the campfire base.
You can disable it in the mod ingame configs.
Look at the campfire -> stoneAndColors and delete the cobblestone line.
