### ISSUE TITLE
Any Items Can Be Put In Respirator Slot

### ISSUE THREAD

**Issue by TheVisionaryOne** [Liahim85/MistyWorld_Open#69]
Any items...not just respirators can be put in the inventory respirator slot. Blocks, food, decor, you name it!

Once players find it, it basically acts as a hidden inventory storage slot, which admittedly is kinda cool, but also ends up being a little cheaty in survival situations.

![2020-06-09_16 07 34](https://user-images.githubusercontent.com/56095032/84209588-61f6ac80-aa6b-11ea-85be-6c9944409bce.png)

**Comment by Liahim85** [comment]
Oh! I'll see, what I can do.

**Comment by Liahim85** [comment]
Fixed! Update 1.2.4.8.
