### ISSUE TITLE
Crashen upon entering Misty World. [1.12]

### ISSUE THREAD

**Issue by Fundryi** [Liahim85/MistyWorld_Open#7]
It's not an insta crash, it crashes after the world is kinda "loaded" or while its loading.

Crash: https://gist.github.com/Fundryi/2e170e4cdd4bc099191e960b3bccc82e

**Comment by Liahim85** [comment]
O! This error has already met, but I could not figure out what is the reason.
If possible, send me somehow saving the world with this error. This will help me solve it.

**Comment by Liahim85** [comment]
Please check the latest version MistWorld_1.12.1_alpha_a_05.jar
It seems to me, I was able to fix the bug.
