### ISSUE TITLE
Respirator Slot Hides Baubles and Aether Inventory Icons

### ISSUE THREAD

**Issue by TheVisionaryOne** [Liahim85/MistyWorld_Open#70]
When opening the Respirator Slot, the Baubles and Aether Legacy inventory icons both disappear! They do return when the Respirator Slot is closed, but it's still a minor annoyance. If it is possible, compatibility with these mods' inventories would be great!

Here's an example of what I'm talking about:
![bxounEYKYQ](https://user-images.githubusercontent.com/56095032/84209950-5061d480-aa6c-11ea-9d84-1aaf74db56b6.png)
![PD0TR3fIeD](https://user-images.githubusercontent.com/56095032/84209951-51930180-aa6c-11ea-8fae-300a149e9361.png)

**Comment by Liahim85** [comment]
The fact: in order to add a slot to main inventory, I have to completely replace it.  Therefore, this is not a bug.  There are no icons, because this is a completely different inventory.
I assume that if you click on the Baubles or Aether icons, the Misty World slot will also disappear.

**Comment by TheVisionaryOne** [comment]
Oh, my bad. Never mind then haha
