### ISSUE TITLE
[SUGGESTION] Blacklist for mobs not affected by acid

### ISSUE THREAD

**Issue by DevTimur** [Liahim85/MistyWorld_Open#77]
Please add  blacklist config for mobs that is will not be affected by mist and acid rain.

**Comment by DevTimur** [comment]
Once again I want to ask to add configurable list of mobs not being affected by mist.

**Comment by Liahim85** [comment]
Oh! Sorry for not answering ...
I'm very busy with the port of the mod for version 1.16.5, so I don't really want to be distracted.
However, to make any mobs immune to fog, you can simply use the damage event.
Just cancel the "mist.in_fog" or "mist.dissolution" damage for specific mobs.

**Comment by DevTimur** [comment]
How can i do that?
I want to prevent mobs from other mod from suffocation.

**Comment by Liahim85** [comment]
[Thephoenixlodge](https://github.com/thephoenixlodge) did it.
I think you can ask him.
He is on the MW discord server )))

**Comment by DevTimur** [comment]
It apears he used Crafttweaker script to prevent damage

Here is link to a script he used to protect certain mobs from receiving damage. I will leave it here for anyone with same issue:
https://github.com/thephoenixlodge/Heavens-of-Sorcery/blob/1fe701a215d77310b62bd611818cd679b4f28df4/scripts/mist_damage.zs

**Comment by DevTimur** [comment]
Oops...
The script worked fine, i will close this issue.

**Comment by DevTimur** [comment]
I also expanded script by adding additional check for **DISSOLUTION** damage

![image](https://user-images.githubusercontent.com/22171136/110905031-80e3e100-8312-11eb-80cb-055bf2e18c65.png)

That prevented mobs from getting damage by rain aswell
