### ISSUE TITLE
[BUG] planks localisation and icon

### ISSUE THREAD

**Issue by DevTimur** [Liahim85/MistyWorld_Open#79]
None of mist wood planks has propper name or icon.
![image](https://user-images.githubusercontent.com/22171136/89281085-37336980-d652-11ea-8b57-5c3b702b934b.png)
IF I try to middleclick it (pick up in cerative) in will give me errored item.
![image](https://user-images.githubusercontent.com/22171136/89281229-75308d80-d652-11ea-8dba-7402c1e6bcd5.png)

**Comment by Liahim85** [comment]
This is strange because everything works fine for me.
This is probably a conflict with another mod.

**Comment by Liahim85** [comment]
Oh! Wait!
Did you change something if lang file?

**Comment by Liahim85** [comment]
Yep! It's a bug. Will be fixed in the next update.
