### ISSUE TITLE
Misty world portal doesn't open on Sponge

### ISSUE THREAD

**Issue by LemADEC** [Liahim85/MistyWorld_Open#87]
As of MistyWorld-1.12.2-1.2.4.15 (from Uncle Genny's 100% Organic & Free-Range Modpack v1.2.0), in SMP with spongeforge-1.12.2-2838-7.3.1-RC4071 (SMP, no plugins), players can't open the portal.
Specially, when placing the block, an explosion does happen, the gold block disappears, but nothing otherwise.
There's no area protection blocking the block changing.
There's neither crash nor logs in console when trying to open the portal.

Issue is still reproduced with spongeforge-1.12.2-2838-7.3.1-RC4077.

**Comment by Liahim85** [comment]
Sorry, Sponge compatibility has not been tested.
