### ISSUE TITLE
[Rendering Distance] Sand block's replace other soils... May be one of the cause for high cpu calculation

### ISSUE THREAD

**Issue by alxcool** [Liahim85/MistyWorld_Open#95]
Hi! My name is Alex. Thk again for realeasing such complex, rich content, and exiting tech mod. So far, mods who try to make the game more realistic are the one of my favorites.

The **specs** of my gaming session have been included at the end of this post's issue.

### Problem : 

While playing survival mode inside a jungle biome, after a while, It feel like if many of the red sand's patchs replace lots of adjacent tropical soils. In comparison, In a previous session, I was playing inside the winter like biome. While farming humus, I was trying hard to replace every gravel blocks by more of the  rocky's soil. So in my current game's session, I was worried if It could be possible that sand's blocks was replacing others soils at a too fast pace. Is it possible that red sand was spreading faster than what I possibly could farm or upkeep arround my mist's house. Somewhat as fast as 1-4 Blocks of dirt replaced per sand's veins every 40 minutes (2 minecraft's day.)

### Hypothesis : 

Since my Rendering distance is set at 16, while I play minecraft, I was wondering if the problem could be on my side. Am'I keeping more loaded chunks than what I possibly could play with?

### Test 1 : Not concluent. 

Today, I've used clay ball and humus as upgrade recipe to replace red sand with additionnal tropical dirt. After earning like 7 stack of dirt's blocks with wet content as high as 4 humus. Next, I've tried to deplete a red sand's vein who at first was looking small. Eventually Such patch was going so far, I've end up digging out 20 stacks of red sand's. (more realiystly 15 stack since I already had 4-5 stack inside the same chest.) Then I was worried, does redsand spread too fast? I was expecting dirt block to run dry, or to lose humus content more than turning into sand block whenever the top soil block with 2% humus was standing over or next to a sand block. Such thing happen quite often arround a tree. So I've dug out an another red sand's vein, witch vein I've expected to be small, then end up with a maximum of 8-9 stack of sands.

Since I was wondering if the sand was growing too fast, I've create a new world to test some parameters. After having found an another red sand's vein to deplete I've tried a comparison. Tried to compare this new world's max amount of red sands blocks; with a older chunk from my previous world. Such test din't help me learn any thing more since the chosen patch, who also was looking like a small one, filled my inventory with 15 stacks of red sands. To be honnest, I've stop counting after that.

### So to conclude

, I've open an issue just to let you know my concern. Let me know if anyting of use could be dug out of this post and thk a lots for your dedication to this mod!
![Test Red Sand Vein](https://user-images.githubusercontent.com/35050233/99745202-2eeb2700-2aa7-11eb-828c-d2cce8200d80.png)
![2020-11-19_19 54 31](https://user-images.githubusercontent.com/35050233/99745266-52ae6d00-2aa7-11eb-89d2-99a3e12ec142.png)
![2020-11-19_19 54 42](https://user-images.githubusercontent.com/35050233/99745281-56da8a80-2aa7-11eb-8d9d-3117c4357ff5.png)
![2020-11-19_19 55 27](https://user-images.githubusercontent.com/35050233/99745289-593ce480-2aa7-11eb-94b7-28b9562f90e8.png)
![2020-11-19_19 55 38](https://user-images.githubusercontent.com/35050233/99745295-5b9f3e80-2aa7-11eb-8f8e-f1972e08bd00.png)

### Technical Information : 

[[
 [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[17:16:56] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64
[17:16:56] [main/INFO] [FML]: Searching C:\Users\ether\AppData\Roaming\.minecraft\mods for mods
[17:16:56] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in MistyWorld-1.12.2-1.2.5.1.jar.

[17:17:01] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 322521736 bytes (307 MB) / 536870912 bytes (512 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
MistHookLoader (MistyWorld-1.12.2-1.2.5.1.jar)
  ru.liahim.mist.core.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.53' Renderer: 'GeForce GTX 1650/PCIe/SSE2'

Forge Mod Loader has identified 5 mods to load.
[latest.log](https://github.com/Liahim85/MistyWorld_Open/files/5570751/latest.log)

]]

_My first language is French. Since english is'nt my first language let me know if I could fix my sentences or my grammar withing or inside my sentences! Note also that I'l be pleased to run more test if asked too._

**Comment by Liahim85** [comment]
To be honest, I didn't quite understand the essence of the problem. Sand and gravel do not replace soil blocks.
There are no such mechanics in the mod.
What you see around trees or water bodies is the result of soil depletion. But this does not happen around the sand veins, and they do not increase over time.

**Comment by alxcool** [comment]
Let replace this hypothesis where sand cause soil to dryout by an another one. Could it be possible that...
>Sand block cause adjacent blocks to update themselves, then they start drying or losing humus content.

Sorry for such misunderstanding. What if I spell this topic differently? Instead of considering sand as the cause, is it possible that my world's update its chunks faster or somehow more often when there is a sand's blocks arround? In such example, sand could be on one side, or bellow the soil block. Some area I've found do not have any sand's blocks betweet the top block and the rock. I guess theses are less likely to run dry. On the other hand, area where I've dug all the sand away could have a air block bellow themselves. Then having air under a soil block, cause it to dry from time to time; almost faster than when it was a sand block. Somehow, dried block who have air bellow themselves wont turn to sand and they won't lose humus content.

Inside the world where I played for many hours, I could find some lake's bed where water does deplete humus content and or trade such depleted block with a red sand block. Unfortunatly, the way the soil deplete its humus content is distributed along a line (picture bellow). As such, I may have misunderstood that sand was the cause. The same happen with soil who have sand on one of his side. Eventually the soil will run dry, then start losing humus.

Now it make me realise something. I was anoyed because tropical dirt is quite complexe to obtain. As such if I want to trade a block of red sand for more tropical dirt, a sample of clay is required. Since clay is'nt always easy to obtain this could explain such feeling. And my main required materia in said recipe spend more humus than anything else, so including clay is'nt quite a problem. So your wright, its not a bug.

edit : about the second picture, note the thin overline arround sand where soils have lower quality. I have to place mulch from time to time arround sand's patch.
![2020-11-20_14 52 14](https://user-images.githubusercontent.com/35050233/99845780-35c77780-2b43-11eb-8c0a-46dcc204a7a0.png)
![2020-11-20_14 54 31](https://user-images.githubusercontent.com/35050233/99845792-38c26800-2b43-11eb-9ae2-16e56c6c0d6d.png)

**Comment by alxcool** [comment]
Should I close this topic? I feel like having lost time or game play on a feature not worthing a fuzz. Maybe next time I should ask question on discord instead. Thk for the support. Despite having dug most of the red sand, arround my house in a jungle biome the soil keep drying. The only thing I should worry about should be how to manage a self sustaining environment. Note the mycelium blocks and the tree's seed system is awsome, thk aigain for your work!

**Comment by Liahim85** [comment]
I could not understand the essence of the problem... Everything works fine for me. Therefore, I cannot help with anything.
I'm sorry.
